[project]
name = "cf-registrar-tracker"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "click>=8.3.0",
    "nodriver>=0.50.3",
    "pyqwe>=3.1.1",
]

[tool.pyqwe]
test = "*:echo hello"
fetch-tlds = "*:uv run -m cf fetch-tlds"
fetch-pricing = "*:uv run -m cf cost"


[dependency-groups]
dev = [
    "ruff>=0.14.1",
]
